version: '3.9'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'TDList-db'
    ports:
      - 5434:5432
    environment:
      - 'POSTGRES_USER=NagatkinAN'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=TDList'
